Food.destroy_all
#User.destroy_all

Food.create(name: "apple", serving_size: "1 medium", calories: 95, total_fat: "0.3g", cholesterol: "0mg", sodium: "1.8mg", total_carbohydrate: "25g", sugar: "19g", protein: "0.5g")
Food.create(name: "blackberry", serving_size: "1 cup", calories: 59, total_fat: "0.6g", cholesterol: "0mg", sodium: "1.5mg", total_carbohydrate: "13g", sugar: "6.7g", protein: "1.9g")
Food.create(name: "blueberry", serving_size: "1/2 cup", calories: 41, total_fat: "0g", cholesterol: "0mg", sodium: "0.5mg", total_carbohydrate: "10.6g", sugar: "7.4g", protein: "0.5g")
Food.create(name: "banana", serving_size: "1 medium", calories: 105, total_fat: "0.4g", cholesterol: "0mg", sodium: "1.2mg", total_carbohydrate: "27g", sugar: "14g", protein: "1.3g")
Food.create(name: "carrot", serving_size: "1 medium", calories: 16, total_fat: "0.1g", cholesterol: "0mg", sodium: "27mg", total_carbohydrate: "3.8g", sugar: "1.6g", protein: "0.3g")
Food.create(name: "cauliflower", serving_size: "1 medium head", calories: 132, total_fat: "2.6g", cholesterol: "0mg", sodium: "86mg", total_carbohydrate: "24g", sugar: "12g", protein: "11g")
Food.create(name: "date", serving_size: "1 pitted date", calories: 20, total_fat: "0g", cholesterol: "0mg", sodium: "0.1mg", total_carbohydrate: "5.3g", sugar: "4.5g", protein: "0.2g")
Food.create(name: "duck", serving_size: "1 cup", calories: 472, total_fat: "40g", cholesterol: "118mg", sodium: "83g", total_carbohydrate: "0g", sugar: "0g", protein: "27g")
Food.create(name: "eggplant", serving_size: "1 medium", calories: 198, total_fat: "1.3g", cholesterol: "0mg", sodium: "5.7g", total_carbohydrate: "49g", sugar: "18g", protein: "4.7g")
Food.create(name: "egg", serving_size: "1 large", calories: 72, total_fat: "4.8g", cholesterol: "186mg", sodium: "71mg", total_carbohydrate: "0.4g", sugar: "0.2g", protein: "6.3g")
Food.create(name: "falafel", serving_size: "1 piece", calories: 57, total_fat: "3g", cholesterol: "0mg", sodium: "50mg", total_carbohydrate: "5.4g", sugar: "0g", protein: "2.3g")
Food.create(name: "fennel", serving_size: "1 cup", calories: 27, total_fat: "0.2g", cholesterol: "0mg", sodium: "45mg", total_carbohydrate: "6.4g", sugar: "3.4g", protein: "1.1g")
Food.create(name: "grape", serving_size: "10 grapes", calories: 34, total_fat: "0.1g", cholesterol: "0mg", sodium: "1mg", total_carbohydrate: "8.9g", sugar: "7.6g", protein: "0.4g")
Food.create(name: "ground beef", serving_size: "4 ounces", calories: 308, total_fat: "20g", cholesterol: "101mg", sodium: "103mg", total_carbohydrate: "0g", sugar: "0g", protein: "31g")
Food.create(name: "chicken", serving_size: "3 ounces", calories: 187, total_fat: "11g", cholesterol: "80mg", sodium: "60mg", total_carbohydrate: "0g", sugar: "0g", protein: "20g")
Food.create(name: "brussel sprout", serving_size: "8 sprouts", calories: 60, total_fat: "0.8g", cholesterol: "0mg", sodium: "35mg", total_carbohydrate: "12g", sugar: "2.9g", protein: "4.3g")
Food.create(name: "bacon", serving_size: "3 slices", calories: 161, total_fat: "12g", cholesterol: "34mg", sodium: "581mg", total_carbohydrate: "0.6g", sugar: "0g", protein: "12g")
Food.create(name: "orange", serving_size: "1 medium", calories: 69, total_fat: "0.2g", cholesterol: "0mg", sodium: "1.4mg", total_carbohydrate: "18g", sugar: "12g", protein: "1.3g")
Food.create(name: "pineapple", serving_size: "0.5 cup", calories: 41, total_fat: "0.1g", cholesterol: "0mg", sodium: "0.8mg", total_carbohydrate: "11g", sugar: "8.1g", protein: "0.5g")
Food.create(name: "mango", serving_size: "1 medium", calories: 202, total_fat: "1.3g", cholesterol: "0mg", sodium: "3.4mg", total_carbohydrate: "50g", sugar: "46g", protein: "2.8g")
Food.create(name: "passion fruit", serving_size: "1 cup", calories: 229, total_fat: "1.7g", cholesterol: "0mg", sodium: "66mg", total_carbohydrate: "55g", sugar: "26g", protein: "5.2g")
Food.create(name: "hotdog", serving_size: "1 frank", calories: 155, total_fat: "14g", cholesterol: "28mg", sodium: "409mg", total_carbohydrate: "1.3g", sugar: "0.6g", protein: "5.6g")
Food.create(name: "kale", serving_size: "1 cup", calories: 36, total_fat: "0.5g", cholesterol: "0mg", sodium: "30mg", total_carbohydrate: "7.3g", sugar: "1.6g", protein: "2.5g")
Food.create(name: "swiss chard", serving_size: "1 cup", calories: 35, total_fat: "0.1g", cholesterol: "0mg", sodium: "313mg", total_carbohydrate: "7.2g", sugar: "1.9g", protein: "3.3g")
Food.create(name: "corn", serving_size: "1 ear", calories: 99, total_fat: "1.5g", cholesterol: "0mg", sodium: "1mg", total_carbohydrate: "22g", sugar: "4.7g", protein: "3.5g")
Food.create(name: "fig", serving_size: "1 medium", calories: 37, total_fat: "0.1g", cholesterol: "0mg", sodium: "0.5mg", total_carbohydrate: "9.6g", sugar: "8.1g", protein: "0.4g")
Food.create(name: "cheese", serving_size: "1 slice", calories: 113, total_fat: "9.3g", cholesterol: "28mg", sodium: "183mg", total_carbohydrate: "0.9g", sugar: "0.1g", protein: "6.4g")
Food.create(name: "lettuce", serving_size: "1 cup", calories: 8, total_fat: "0.1g", cholesterol: "0mg", sodium: "3.8mg", total_carbohydrate: "1.6g", sugar: "0.6g", protein: "0.6g")
Food.create(name: "tomato", serving_size: "1 medium", calories: 22, total_fat: "0.3g", cholesterol: "0mg", sodium: "6.2mg", total_carbohydrate: "4.8g", sugar: "3.2g", protein: "1.1g")
Food.create(name: "potato", serving_size: "1 medium", calories: 161, total_fat: "0.2g", cholesterol: "0mg", sodium: "17mg", total_carbohydrate: "37g", sugar: "2g", protein: "4.3g")
Food.create(name: "grapefruit", serving_size: "1 medium", calories: 104, total_fat: "0.3g", cholesterol: "0mg", sodium: "0mg", total_carbohydrate: "26g", sugar: "17g", protein: "1.9g")
Food.create(name: "kiwi", serving_size: "1 medium", calories: 42, total_fat: "0.4g", cholesterol: "0mg", sodium: "2.1mg", total_carbohydrate: "10g", sugar: "6.2g", protein: "0.8g")
Food.create(name: "milk", serving_size: "1 cup", calories: 125, total_fat: "4.7g", cholesterol: "20mg", sodium: "127mg", total_carbohydrate: "12g", sugar: "0g", protein: "8.5g")
Food.create(name: "coffee", serving_size: "1 cup", calories: 2, total_fat: "0.1g", cholesterol: "0mg", sodium: "4.7mg", total_carbohydrate: "0g", sugar: "0g", protein: "0.3g")
Food.create(name: "onion", serving_size: "1 medium", calories: 41, total_fat: "0.2g", cholesterol: "0mg", sodium: "2.8mg", total_carbohydrate: "9.5g", sugar: "4.4g", protein: "1.3g")
Food.create(name: "kumquat", serving_size: "1 medium", calories: 13, total_fat: "0.2g", cholesterol: "0mg", sodium: "1.9mg", total_carbohydrate: "3g", sugar: "1.8g", protein: "0.4g")
Food.create(name: "scallion", serving_size: "1 medium", calories: 5, total_fat: "0g", cholesterol: "0mg", sodium: "2.4mg", total_carbohydrate: "1.1g", sugar: "0.3g", protein: "0.3g")
Food.create(name: "garlic", serving_size: "1 clove", calories: 5, total_fat: "0g", cholesterol: "0mg", sodium: "0.5mg", total_carbohydrate: "1g", sugar: "0g", protein: "0.2g")
Food.create(name: "tuna", serving_size: "3 ounces", calories: 111, total_fat: "0.5g", cholesterol: "40mg", sodium: "46mg", total_carbohydrate: "0g", sugar: "0g", protein: "25g")
Food.create(name: "almond", serving_size: "1 almond", calories: 8, total_fat: "0.7g", cholesterol: "0mg", sodium: "6.4mg", total_carbohydrate: "0.3g", sugar: "0.1g", protein: "0.3g")
Food.create(name: "raisin", serving_size: "1 small box", calories: 129, total_fat: "0.2g", cholesterol: "0mg", sodium: "4.7mg", total_carbohydrate: "34g", sugar: "25g", protein: "1.3g")
Food.create(name: "broccoli", serving_size: "1 spear", calories: 13, total_fat: "0.1g", cholesterol: "0mg", sodium: "15mg", total_carbohydrate: "2.7g", sugar: "0.5g", protein: "0.9g")
Food.create(name: "ginger", serving_size: "1 tsp", calories: 2, total_fat: "0g", cholesterol: "0mg", sodium: "0.3mg", total_carbohydrate: "0.4g", sugar: "0g", protein: "0g")
Food.create(name: "zucchini", serving_size: "1 medium", calories: 33, total_fat: "0.8g", cholesterol: "0mg", sodium: "6.5mg", total_carbohydrate: "5.8g", sugar: "3.7g", protein: "2.5g")
Food.create(name: "strawberry", serving_size: "5 large", calories: 29, total_fat: "0.3g", cholesterol: "0mg", sodium: "0.9mg", total_carbohydrate: "6.9g", sugar: "4.4g", protein: "0.6g")
Food.create(name: "cheesecake", serving_size: "1 piece", calories: 401, total_fat: "28g", cholesterol: "69mg", sodium: "548mg", total_carbohydrate: "32g", sugar: "27g", protein: "6.9g")
Food.create(name: "granola", serving_size: "0.5 cup", calories: 298, total_fat: "15g", cholesterol: "0mg", sodium: "16mg", total_carbohydrate: "33g", sugar: "12g", protein: "8.3g")
Food.create(name: "scallop", serving_size: "1 scallop(13g)", calories: 14, total_fat: "0.1g", cholesterol: "5.3mg", sodium: "87mg", total_carbohydrate: "0.7g", sugar: "0g", protein: "2.7g")
Food.create(name: "potato chip", serving_size: "1 ounce", calories: 149, total_fat: "9.5g", cholesterol: "0mg", sodium: "148mg", total_carbohydrate: "15g", sugar: "0.1g", protein: "1.8g")
Food.create(name: "turkey", serving_size: "4 ounces", calories: 214, total_fat: "8.4g", cholesterol: "124mg", sodium: "117mg", total_carbohydrate: "0.1g", sugar: "0g", protein: "32g")
Food.create(name: "bread", serving_size: "1 slice", calories: 77, total_fat: "1g", cholesterol: "0mg", sodium: "142mg", total_carbohydrate: "14g", sugar: "1.6g", protein: "2.6g")
Food.create(name: "brownie", serving_size: "1 medium(50g)", calories: 233, total_fat: "15g", cholesterol: "37mg", sodium: "172mg", total_carbohydrate: "25g", sugar: "25g", protein: "3.1g")
Food.create(name: "avocado", serving_size: "1 avocado(201g)", calories: 322, total_fat: "29mg", cholesterol: "0mg", sodium: "14mg", total_carbohydrate: "17g", sugar: "1.3g", protein: "4g")
Food.create(name: "guacamole", serving_size: "2 tbsp(30g)", calories: 45, total_fat: "4.1g", cholesterol: "0mg", sodium: "127mg", total_carbohydrate: "2.6g", sugar: "0.2g", protein: "0.6g")
Food.create(name: "gin", serving_size: "1 shot(42g)", calories: 97, total_fat: "0g", cholesterol: "0mg", sodium: "0.4mg", total_carbohydrate: "0g", sugar: "0g", protein: "0g")
Food.create(name: "vodka", serving_size: "1 shot(42g)", calories: 97, total_fat: "0g", cholesterol: "0mg", sodium: "0.4mg", total_carbohydrate: "0g", sugar: "0g", protein: "0g")
Food.create(name: "zaatar", serving_size: "1 tbsp(4.2g)", calories: 15, total_fat: "0.9g", cholesterol: "0mg", sodium: "176mg", total_carbohydrate: "1.7g", sugar: "0.1g", protein: "0.6g")
Food.create(name: "yam", serving_size: "1 cup(136g)", calories: 158, total_fat: "0.2g", cholesterol: "0mg", sodium: "11mg", total_carbohydrate: "37g", sugar: "0.7g", protein: "2g")
Food.create(name: "yogurt", serving_size: "6 ounces(170g)", calories: 107, total_fat: "2.6g", cholesterol: "10mg", sodium: "119mg", total_carbohydrate: "12g", sugar: "12g", protein: "8.9g")
Food.create(name: "greek yogurt", serving_size: "6 ounces(170g)", calories: 100, total_fat: "0.7g", cholesterol: "8.5mg", sodium: "61mg", total_carbohydrate: "6.1g", sugar: "5.5g", protein: "17g")
Food.create(name: "ham", serving_size: "1 cup(134g)", calories: 186, total_fat: "6.8g", cholesterol: "86mg", sodium: "1309mg", total_carbohydrate: "1.4g", sugar: "1.4g", protein: "30g")
# Food.create(name: "mushroom", serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )


User.create(username: "Maddy", password: "123abc")
User.create(username: "Kevin", password: "kevinklein")