Food.create(name: "apple", serving_size: "1 medium", calories: 95, total_fat: "0.3g", cholesterol: "0mg", sodium: "1.8mg", total_carbohydrate: "25g", sugar: "19g", protein: "0.5g")
Food.create(name: "blackberries", serving_size: "1 cup", calories: 59, total_fat: "0.6g", cholesterol: "0mg", sodium: "1.5mg", total_carbohydrate: "13g", sugar: "6.7g", protein: "1.9g")
Food.create(name: "blueberries", serving_size: "1/2 cup", calories: 41, total_fat: "0g", cholesterol: "0mg", sodium: "0.5mg", total_carbohydrate: "10.6g", sugar: "7.4g", protein: "0.5g")
Food.create(name: "banana", serving_size: "1 medium", calories: 105, total_fat: "0.4g", cholesterol: "0mg", sodium: "1.2mg", total_carbohydrate: "27g", sugar: "14g", protein: "1.3g")
Food.create(name: "carrot", serving_size: "1 medium", calories: 16, total_fat: "0.1g", cholesterol: "0mg", sodium: "27mg", total_carbohydrate: "3.8g", sugar: "1.6g", protein: "0.3g")
Food.create(name: "cauliflower", serving_size: "1 medium head", calories: 132, total_fat: "2.6g", cholesterol: "0mg", sodium: "86mg", total_carbohydrate: "24g", sugar: "12g", protein: "11g")
Food.create(name: "dates", serving_size: "1 pitted date", calories: 20, total_fat: "0g", cholesterol: "0mg", sodium: "0.1mg", total_carbohydrate: "5.3g", sugar: "4.5g", protein: "0.2g")
Food.create(name: "duck", serving_size: "1 cup", calories: 472, total_fat: "40g", cholesterol: "118mg", sodium: "83g", total_carbohydrate: "0g", sugar: "0g", protein: "27g")
Food.create(name: "eggplant", serving_size: "1 medium", calories: 198, total_fat: "1.3g", cholesterol: "0mg", sodium: "5.7g", total_carbohydrate: "49g", sugar: "18g", protein: "4.7g")
Food.create(name: "egg", serving_size: "1 large", calories: 72, total_fat: "4.8g", cholesterol: "186mg", sodium: "71mg", total_carbohydrate: "0.4g", sugar: "0.2g", protein: "6.3g")
Food.create(name: "falafel", serving_size: "1 piece", calories: 57, total_fat: "3g", cholesterol: "0mg", sodium: "50mg", total_carbohydrate: "5.4g", sugar: "0g", protein: "2.3g")
Food.create(name: "fennel", serving_size: "1 cup", calories: 27, total_fat: "0.2g", cholesterol: "0mg", sodium: "45mg", total_carbohydrate: "6.4g", sugar: "3.4g", protein: "1.1g")
Food.create(name: "grapes", serving_size: "10 grapes", calories: 34, total_fat: "0.1g", cholesterol: "0mg", sodium: "1mg", total_carbohydrate: "8.9g", sugar: "7.6g", protein: "0.4g")
Food.create(name: "ground beef", serving_size: "4 ounces", calories: 308, total_fat: "20g", cholesterol: "101mg", sodium: "103mg", total_carbohydrate: "0g", sugar: "0g", protein: "31g")
Food.create(name: "chicken", serving_size: "3 ounces", calories: 187, total_fat: "11g", cholesterol: "80mg", sodium: "60mg", total_carbohydrate: "0g", sugar: "0g", protein: "20g")
Food.create(name: "brussel sprouts", serving_size: "8 sprouts", calories: 60, total_fat: "0.8g", cholesterol: "0mg", sodium: "35mg", total_carbohydrate: "12g", sugar: "2.9g", protein: "4.3g")
Food.create(name: "bacon", serving_size: "3 slices", calories: 161, total_fat: "12g", cholesterol: "34mg", sodium: "581mg", total_carbohydrate: "0.6g", sugar: "0g", protein: "12g")
Food.create(name: "orange", serving_size: "1 medium", calories: 69, total_fat: "0.2g", cholesterol: "0mg", sodium: "1.4mg", total_carbohydrate: "18g", sugar: "12g", protein: "1.3g")
Food.create(name: "pineapple", serving_size: "0.5 cup", calories: 41, total_fat: "0.1g", cholesterol: "0mg", sodium: "0.8mg", total_carbohydrate: "11g", sugar: "8.1g", protein: "0.5g")
Food.create(name: "mango", serving_size: "1 medium", calories: 202, total_fat: "1.3g", cholesterol: "0mg", sodium: "3.4mg", total_carbohydrate: "50g", sugar: "46g", protein: "2.8g")
Food.create(name: "passion fruit", serving_size: "1 cup", calories: 229, total_fat: "1.7g", cholesterol: "0mg", sodium: "66mg", total_carbohydrate: "55g", sugar: "26g", protein: "5.2g")
Food.create(name: "hotdog", serving_size: "1 frank", calories: 155, total_fat: "14g", cholesterol: "28mg", sodium: "409mg", total_carbohydrate: "1.3g", sugar: "0.6g", protein: "5.6g")
Food.create(name: "kale", serving_size: "1 cup", calories: 36, total_fat: "0.5g", cholesterol: "0mg", sodium: "30mg", total_carbohydrate: "7.3g", sugar: "1.6g", protein: "2.5g")
Food.create(name: "swiss chard", serving_size: "1 cup", calories: 35, total_fat: "0.1g", cholesterol: "0mg", sodium: "313mg", total_carbohydrate: "7.2g", sugar: "1.9g", protein: "3.3g")
Food.create(name: "corn", serving_size: "1 ear", calories: 99, total_fat: "1.5g", cholesterol: "0mg", sodium: "1mg", total_carbohydrate: "22g", sugar: "4.7g", protein: "3.5g")
Food.create(name: "figs", serving_size: "1 medium", calories: 37, total_fat: "0.1g", cholesterol: "0mg", sodium: "0.5mg", total_carbohydrate: "9.6g", sugar: "8.1g", protein: "0.4g")
# Food.create(name: "cheese", serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: "lettuce", serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: "tomato", serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )
# Food.create(name: , serving_size: , calories: , total_fat: , cholesterol: , sodium: , total_carbohydrate:, sugar:, protein: )


User.create(username: "Maddy", password: "123abc")
User.create(username: "Kevin", password: "kevinklein")